### ISSUE TITLE
this.setState possible bug

### ISSUE THREAD

**Issue by nilovna** [bmorrison4/lr_client#1]
https://github.com/bmorrison4/lr_client/blob/c03c727ca1e4fa64480b280f2bac0e656140d27e/src/components/chat/messages.jsx#L186-L187

The `push` return value on an array is the length of the array, not the array with the new element.

[`this.setState([updater])`](https://reactjs.org/docs/react-component.html#setstate) should also return an object.

I think this way would work
```js
  onMessage = data => {
    data.username = data.name;
    delete data.name;
    if (data.room === this.props.robocaster) {
      this.setState(state => {
        return { messages: [...state.messages, data] };
      });
    }
  };
```

**Comment by bmorrison4** [comment]
Thanks! Implemented and working.
